# Generated by Django 4.1.2 on 2022-10-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='enderecos.endereco'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rg',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
