# Generated by Django 4.1.2 on 2022-10-15 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0003_alter_endereco_managers'),
        ('users', '0003_user_endereco_alter_user_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_usuario',
            field=models.ImageField(null=True, upload_to='fotos_usuarios/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='enderecos.endereco'),
        ),
    ]
