# Generated by Django 4.1.2 on 2022-10-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_foto_usuario_alter_user_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_usuario',
            field=models.ImageField(default=None, null=True, upload_to='fotos_usuarios/'),
        ),
    ]
