# Generated by Django 4.1.2 on 2022-10-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_foto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_usuario',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='fotos_usuarios/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rg',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
