# Generated by Django 4.1.2 on 2022-10-17 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roupas', '0001_initial'),
        ('lojas', '0002_alter_loja_loja_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(to='roupas.roupa'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='lojas.loja'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedido', to='pedidos.statuspedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario_pedinte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidocloncluido',
            name='itens_comprados',
            field=models.ManyToManyField(to='roupas.roupa'),
        ),
    ]
