# Generated by Django 4.1.2 on 2022-10-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roupas', '0001_initial'),
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PedidoCloncluido',
            new_name='PedidoConcluido',
        ),
    ]
