# Generated by Django 4.1.2 on 2022-10-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_rename_pedidocloncluido_pedidoconcluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_devolução',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
