# Generated by Django 4.1.2 on 2022-10-24 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roupas', '0005_alter_roupa_t1_alter_roupa_t2_alter_roupa_t3_and_more'),
        ('pedidos', '0004_alter_pedido_data_devolução_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveBigIntegerField(default=0)),
                ('roupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='roupas.roupa')),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(to='pedidos.item'),
        ),
    ]
