# Generated by Django 4.1.2 on 2022-10-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_item_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
