# Generated by Django 4.1.2 on 2022-10-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupas', '0002_alter_roupa_t1_alter_roupa_t2_alter_roupa_t3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='t1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='t2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='t3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='t4',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='t5',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='t6',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
