# Generated by Django 4.1.2 on 2022-10-15 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='colecao', serialize=False, to='lojas.loja')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
