# Generated by Django 4.1.2 on 2022-10-15 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0001_initial'),
        ('colecoes', '0002_delete_colecao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecao', to='lojas.loja')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
