# Generated by Django 4.1.2 on 2022-10-15 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_user_endereco_alter_user_rg'),
        ('enderecos', '0003_alter_endereco_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('loja_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome_loja', models.CharField(max_length=50)),
                ('email_loja', models.EmailField(max_length=255, null=True)),
                ('telefone_loja', models.CharField(max_length=16, null=True)),
                ('cnpj', models.CharField(max_length=18)),
                ('numero_cartao', models.CharField(max_length=64)),
                ('nome_cartao', models.CharField(max_length=64)),
                ('cvv', models.CharField(max_length=64)),
                ('data_expiracao', models.DateTimeField(verbose_name=64)),
                ('date_joined_loja', models.DateTimeField(default=django.utils.timezone.now)),
                ('logo_loja', models.ImageField(null=True, upload_to='logos_lojas/')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loja', to='enderecos.endereco')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojas.plano')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
