# Generated by Django 4.1.2 on 2022-10-15 19:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='endereco',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
