# Generated by Django 4.1.2 on 2022-10-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_alter_endereco_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='endereco',
            managers=[
            ],
        ),
    ]
